### ISSUE TITLE
Team feedback

### ISSUE THREAD

**Issue by Chawki-Mbarki** [DamenaM/setup-and-mobile-first-project#6]
# Team Feedback

**Comment by DamenaM** [comment]
Thanks for your constructive  feedback

**Comment by Bigizi** [comment]
Hi @DamenaM 
I would suggest you to check the padding top of textarea in the contact form and decrease it

**Comment by Chawki-Mbarki** [comment]
Hello @DamenaM 
Good Job, Your code meets all the project requirements perfectly but I noticed a lot of repeated styles
I believe that you can do the same styling with half lines of code
of course, now it's too late to change that, but in the future, you can focus on writing a more organized style
